export const SHOW_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const GET_ALL_USERS = "GET_ALL_USERS";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const SHOW_POPUP = "SHOW_POPUP";
export const HIDE_POPUP = "HIDE_POPUP";
export const SHOW_PRACTICE_MODAL = "SHOW_PRACTICE_MODAL";
export const SHOW_RANK_MODAL = "SHOW_RANK_MODAL";
export const SHOW_PVP_MODAL = "SHOW_PVP_MODAL";
export const SHOW_FIND_MODAL = "SHOW_FIND_MODAL";
export const SHOW_GAME_RESULT_MODAL = "SHOW_GAME_RESULT_MODAL";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const UPDATE_PROFILE_PIC = "UPDATE_PROFILE_PIC";

export const SET_GAME_MODE = "SET_GAME_MODE";
export const GET_ALL_HISTORY = "GET_ALL_HISTORY";
export const ADD_NEW_HISTORY = "ADD_NEW_HISTORY";
export const UPDATE_HISTORY = "UPDATE_HISTORY";

export const SET_TO_CHALLENGE = "SET_TO_CHALLENGE";
export const GET_ALL_CHALLENGES = "GET_ALL_CHALLENGES";
export const DECLINE_CHALLENGE = "DECLINE_CHALLENGE";
export const ACCEPT_CHALLENGE = "ACCEPT_CHALLENGE";

export const UPDATE_USER_MMR = "UPDATE_USER_MMR";
